### ISSUE TITLE
License and operating systems supported

### ISSUE THREAD

**Issue by Ghwomb** [mashaal/destroyer#3]
It looks really nice! I've got a lot of lossless files stored on my home (FreeNAS) server. So perhaps I'll look into if I can adopt it to run inside of a jail instead of on S3. But what kind of software license is the code under? ISC would be nice! Also is it for OSX only or have you tested it on other operating systems?

**Comment by mashaal** [comment]
Thanks!

I've had a couple requests for FreeNAS integration -- I don't have any experience  with it... does it provide a url to your files? or does it need to be mounted some other way?

If FreeNAS can provide a url or file object, it should be quite easy to integrate.

I am currently working on a rebuild of this using React and Redux, which supports streaming from S3, as well as the local filesystem. It's quite a major improvement, and I'm hoping to push the update within the next few weeks.

About licensing -- it's all a bit beyond me, the types of licensing available. I will have to look into the fine details, but please feel free to open pull requests.

**Comment by Ghwomb** [comment]
> FreeNAS stuff

I'll try to look into it myself if I get the time. But basically I think the solution is to run a destroyer[jail](http://doc.freenas.org/9.10/jails.html) and accessing the file system inside that jail. Inside a jail you can install nginx or apache which I assume can be configured to expose the FreeNAS file system as a URL:s. Since the jail can be full Linux systems, Electron, Destroyer and any other programs can be installed as needed.

> Licensing

My personal preference is to use the [ISC license](https://opensource.org/licenses/ISC). It allows anyone to do anything to the code, including closing the source and not giving changes back, as long as you are recognized as the author of the program. I use it since I don't make any fancy software that I will make any money from. So I may as well maximize peoples possibilities.

If you want to force people to contribute back non-trivial changes and forbid them to close the source use the [GPL v2.0](https://opensource.org/licenses/GPL-2.0) license. Downside is the amount of legalese it will add compared to the eight lines of the ISC license. And good luck forcing people to contribute back.

I'll be happy to make a pull request adding a license if you select one.

> Linux

I'll try to build it for Linux ([Ubuntu-Mate](https://ubuntu-mate.org/) at least). And, if it is possible for me, contribute a build for the release.

**Comment by mashaal** [comment]
I'm actually quite keen to start experimenting with FreeNAS now -- are you available to chat outside of github? My email is omar@teacups.io 

Would love to have a Linux/Windows build as well -- had some interest from the audiophile subreddit -- https://www.reddit.com/r/audiophile/comments/52msfy/i_built_an_opensource_lossless_audio_player/

**Comment by Ghwomb** [comment]
* I'll contact you about running FreeNAS.
* I have added a license by pull request.
* The same pull request added some support for running Destroyer on Ubuntu Linux.

**Comment by mashaal** [comment]
I had some time to look into building for other operating systems -- I was able to package (from my mac) windows and linux builds. I didn't get to test them thoroughly yet though. I've committed the changes and will document how to run/build.
