### ISSUE TITLE
windows build?

### ISSUE THREAD

**Issue by Suburbanno** [mashaal/destroyer#7]

**Comment by sirtobey** [comment]
Care to elaborate? ;)

**Comment by mashaal** [comment]
Unfortunately, I don't have a windows machine handy -- I did do a test build on a windows vm a few months ago. Everything seemed to be working besides showing album artwork (I think it was a file path thing.)

It would be killer if someone with a dedicated windows machine could iron out some of the issues! (hint hint)

**Comment by Suburbanno** [comment]
I can test these builds?

**Comment by mashaal** [comment]
I will put together some documentation on how to clone and build locally.

**Comment by Suburbanno** [comment]
ok

**Comment by anjelo** [comment]
I was able to run it on Windows. Pull request incoming.

**Comment by mashaal** [comment]
Wow, great! Does everything work as expected?

**Comment by Suburbanno** [comment]
waiting

**Comment by mashaal** [comment]
@anjelo @Suburbanno if it works, please send through a build file, and we can add to the downloads page!

**Comment by anjelo** [comment]
Everything works so far except the album art. I'm trying to fix that but i'm not making any progress yet.

**Comment by bathoorn** [comment]
Album art is not working in windows because windows paths user \ instead of /.
I quickly hacked it by doing a root.replace(/\\/g, '/') in the connection component.

**Comment by Suburbanno** [comment]
news?
